#! /usr/bin/env python

"""
This module implements the TolTEC data model.

The TolTEC data model covers two topics:

1. Basic Obs Data (BOD)

    Basic Obs Data are the data from the telescope/instrument control system
    (TCS/ICS) and the timely analysis service (TAS).

    These data are typically stored on disk on a per-interface basis, and
    carry full runtime information of the TolTEC instrument.

    The name "basic obs" (BO) refers to a continuous file-writing transaction
    executed by the TCS/ICS. This is different from an "obs request" (OR) which
    may consist of multiple BOs.

    Each basic obs is assigned a unique transaction identifier, consists of a
    4-tuple of "master", "obsnum", "subobsnum", and "scannum". In addition,
    the basic obs data stream may be relayed (duplicated) to remote
    destinations and files will be created with the destination local repeat
    writers. The (repeated) copy of the data files are distinguished by an
    integer field "repeat". The original data has "repeat" value of 0.

    The TAS monitors newly generated raw obs data and runs various data
    reduction recipes to create timely view data products to guide the
    observation. One of the most important output of this is noted as the basic
    reduced data files for each input raw obs data files.

    Both raw obs data and basic reduced data can be handled by the wrapper
    class `~tolteca.datamodels.toltec.BasicObsData`. By providing a unified
    interface for access the meta data and data in the data files, this wrapper
    class hides away the details of handling of interacting with each data
    storage format for different data kinds, which is implemented in the
    various subclasses of `~tolteca.datamodels.io.DataFileIO` defined in
    `~tolteca.datamodels.io.toltec`.

    More over, the helper class `~tolteca.datamodels.toltec.BasicObsDataset`
    provides a table-like way to work with a collection of BOD files for
    carrying out instrument level diagnostics and data analysis.


2. Data Products and the Associations

    Data Products (DPs) and Data Product Associations (DPAs) are the core
    concepts of the TolTEC data management system, which involves both the raw
    data and the reduced data.

    The DP and DPA information are managed using the data product database
    (DPDB). The modules `~tolteca.datamodels.db`,
    `~tolteca.datamodels.dp`, and `~tolteca.datamodels.toltecdp` implement
    the database structure, the data product specification/schema, as well
    as the interface to manage the DP and DPAs.

    Data analysis tasks run via TolTECA read and write to DPDB to record
    the inputs, outputs, the associations, as well the runtime context info.

    The key element of a data product is an index object (DPIndex), typically
    stored along with the actual (textual or binary) data files as an
    standalone YAML (or JSON) file.

    One of the key property of a data product is the data product type.
    The contents of the DPIndex for different data types are constrained by the
    corresponding schemas.

    Some data product types are:

    * dp_raw_obs
        Simple collection of raw basic obs data files (BODs).

    * dp_basic_reduced_obs
        Simple collection of basic reduced obs data generated by the TAS,
        one-to-one mapping to the dp_raw_obs.

    * dp_science
        Reduced, science-ready maps/catalogs.

    The DPs are related to each other through association info noted as DPAs.
    Each DPA typically has contextual data (meta data) to describe the
    relations of the DPs.

"""

from .basic_obs_data import *  # noqa: F401 F403
from .data_prod import *  # noqa: F401 F403
